// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace IKHealth
{
	public partial class HomeController : UIViewController
	{
		public HomeController (IntPtr handle) : base (handle)
		{
		}
		
		partial void Logout_Clicked (MonoTouch.Foundation.NSObject sender)
		{
			DismissModalViewControllerAnimated(true);
		}
	}
}
