// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.Drawing;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.CoreImage;
using MonoTouch.CoreGraphics;

namespace IKHealth
{
	public partial class LoginView : UIImageView
	{
		public LoginView (IntPtr handle) : base (handle)
		{
			this.Image = GenerateBackgroundImage();
		}
		
		private UIImage GenerateBackgroundImage()
		{
			UIGraphics.BeginImageContextWithOptions(this.Bounds.Size, true, 1);
			
			// The location of the colors is at the start and end
		    float[] locations = new float[] { 0.0f, 1.0f };
			
			// These are the colors defined as RBGA values		    
			float[] components = new float[]
				{ 
		        	0.18f, 0.53f, 0.78f, 1f,
		        	0.11f, 0.34f, 0.5f, 1f 
				};
			
			var colorSpace = CGColorSpace.CreateDeviceRGB();
			
			CGGradient gradient = new CGGradient(colorSpace, components, locations);			
				
			UIGraphics.GetCurrentContext().DrawRadialGradient(gradient, Center, 0, Center, Bounds.Size.Width, CGGradientDrawingOptions.DrawsAfterEndLocation);
			
			return UIGraphics.GetImageFromCurrentImageContext();				
		}
	}
}
