// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace IKHealth
{
	public partial class PatientsViewController : UITableViewController
	{
		public PatientsViewController (IntPtr handle) : base (handle)
		{
		}	
	}
}
